on:
  - pull_request
  - push

name: Tests

jobs:
  unit:
    name: Unit tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php-version:
          - "8.0"

        dependencies:
          - lowest
          - highest

    steps:
      - name: Configure git to avoid issues with line endings
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug3
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@1.3.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover dist/phpunit/clover.xml

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  types-psaml:
    name: Type tests (Psalm)

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "8.0"

        dependencies:
          - lowest
          - highest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug3
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@1.3.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/pslam --shepherd
